### ISSUE TITLE
Handle action artifacts from previous steps

### ISSUE THREAD

**Issue by sgkiokas** [camelotls/actions-jira-integration#227]
We should add the ability to handle the artifacts produced by previous steps (e.g. a pdf report).

To do so, we need to:

- upload an artifact from the initial action via the `upload-artifact` action
- download it to the current action via the `download-artifact` action
- upload it as attachment to the respective Jira issue via {their API](https://docs.atlassian.com/software/jira/docs/api/REST/8.4.3/#api/2/issue/{issueIdOrKey}/attachments)

An example of how to upload an artifact in the yaml file could be:

```
-  name: Archive NowSecure reports
               uses: actions/upload-artifact@v2
               with:
                  name: reports
                  path: ios.pdf
```

For more information about the relevant actions, look at https://docs.github.com/en/actions/guides/storing-workflow-data-as-artifacts
