### ISSUE TITLE
Amend the instructions on how to pull this action

### ISSUE THREAD

**Issue by sgkiokas** [camelotls/actions-jira-integration#51]
The following step of retrieving the current action is incorrect:

```
- name: Jira ticket creation
              id: jira_integration
              uses: camelotls/actions-jira-integration@latest
```

Instead, it should be:

```
-  name: Checkout Jira integration GitHub Action Repo
               uses: actions/checkout@v2
               with:
                repository: camelotls/actions-jira-integration
                ref: <version-to-be-pulled>
                token: ${{ secrets.MACHINEUSER_GITHUB_TOKEN }}
                path: actions-jira-integration
-  name: Jira ticket creation
               id: jira_integration
               uses: ./actions-jira-integration/
...
```
